version: '2'

services:
  static-web:
    build: .
    ports:
     - "5013:5013"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 2s
